package payroll;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sophi
 */
public class SecondPayrollPanel extends javax.swing.JFrame {

    /**
     * Creates new form SecondPayrollPanel
     */
    public SecondPayrollPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton5 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtID1 = new javax.swing.JTextField();
        txtSelectemployee = new javax.swing.JLabel();
        txtSelectemployee1 = new javax.swing.JLabel();
        txtID4 = new javax.swing.JTextField();
        txtSelectemployee2 = new javax.swing.JLabel();
        txtID5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSelectemployee3 = new javax.swing.JLabel();
        txtID6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSelectemployee4 = new javax.swing.JLabel();
        txtID7 = new javax.swing.JTextField();
        backToPESelection = new javax.swing.JToggleButton();
        txtSelectemployee7 = new javax.swing.JLabel();
        txtID10 = new javax.swing.JTextField();
        txtSelectemployee8 = new javax.swing.JLabel();
        txtID11 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BacktoDB1 = new javax.swing.JToggleButton();
        generatePayslipButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(107, 36, 12));

        jPanel2.setBackground(new java.awt.Color(153, 77, 28));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(228, 143, 69));
        jLabel1.setText("EMPLOYEE PAYROLL DATA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 27));

        jToggleButton5.setBackground(new java.awt.Color(228, 143, 69));
        jToggleButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton5.setForeground(new java.awt.Color(107, 36, 12));
        jToggleButton5.setText("Edit");
        jToggleButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 65, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Tax", null, null},
                {"SSS", null, null},
                {"PhilHealth", null, null}
            },
            new String [] {
                "Deductions", "Amount", "Reason"
            }
        ));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 630, 90));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Time In", "Time Out", "Income per Hour", "Overtime", "Total Hours"
            }
        ));
        jTable2.setShowGrid(true);
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 630, 224));

        txtID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 64, 150, -1));

        txtSelectemployee.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtSelectemployee.setForeground(new java.awt.Color(245, 204, 160));
        txtSelectemployee.setText("Name:");
        jPanel2.add(txtSelectemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, -1, -1));

        txtSelectemployee1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtSelectemployee1.setForeground(new java.awt.Color(245, 204, 160));
        txtSelectemployee1.setText("Position:");
        jPanel2.add(txtSelectemployee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, -1, -1));

        txtID4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID4ActionPerformed(evt);
            }
        });
        jPanel2.add(txtID4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 92, 150, -1));

        txtSelectemployee2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtSelectemployee2.setForeground(new java.awt.Color(245, 204, 160));
        txtSelectemployee2.setText("ID:");
        jPanel2.add(txtSelectemployee2, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 66, -1, -1));

        txtID5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID5ActionPerformed(evt);
            }
        });
        jPanel2.add(txtID5, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 64, 60, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("............................................................................................................................................................");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 519, -1, -1));

        txtSelectemployee3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtSelectemployee3.setForeground(new java.awt.Color(245, 204, 160));
        txtSelectemployee3.setText("Gross Income: ");
        jPanel2.add(txtSelectemployee3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        txtID6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID6ActionPerformed(evt);
            }
        });
        jPanel2.add(txtID6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 272, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("............................................................................................................................................................");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        txtSelectemployee4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtSelectemployee4.setForeground(new java.awt.Color(245, 204, 160));
        txtSelectemployee4.setText("Overtime Income: ");
        jPanel2.add(txtSelectemployee4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        txtID7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID7ActionPerformed(evt);
            }
        });
        jPanel2.add(txtID7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 272, -1));

        backToPESelection.setBackground(new java.awt.Color(228, 143, 69));
        backToPESelection.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backToPESelection.setForeground(new java.awt.Color(107, 36, 12));
        backToPESelection.setText("Back to Selection");
        backToPESelection.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backToPESelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToPESelectionActionPerformed(evt);
            }
        });
        jPanel2.add(backToPESelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 620, 120, -1));

        txtSelectemployee7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtSelectemployee7.setForeground(new java.awt.Color(245, 204, 160));
        txtSelectemployee7.setText("Total Deductions:");
        jPanel2.add(txtSelectemployee7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));

        txtID10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID10ActionPerformed(evt);
            }
        });
        jPanel2.add(txtID10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, 272, -1));

        txtSelectemployee8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtSelectemployee8.setForeground(new java.awt.Color(245, 204, 160));
        txtSelectemployee8.setText("Net Salary: ");
        jPanel2.add(txtSelectemployee8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, -1, -1));

        txtID11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID11ActionPerformed(evt);
            }
        });
        jPanel2.add(txtID11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 640, 272, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("............................................................................................................................................................");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, -1, -1));

        BacktoDB1.setBackground(new java.awt.Color(228, 143, 69));
        BacktoDB1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BacktoDB1.setForeground(new java.awt.Color(107, 36, 12));
        BacktoDB1.setText("Back to Dashboard");
        BacktoDB1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BacktoDB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacktoDB1ActionPerformed(evt);
            }
        });
        jPanel2.add(BacktoDB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, 120, -1));

        generatePayslipButton.setBackground(new java.awt.Color(228, 143, 69));
        generatePayslipButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        generatePayslipButton.setForeground(new java.awt.Color(107, 36, 12));
        generatePayslipButton.setText("Generate Payslip");
        generatePayslipButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        generatePayslipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePayslipButtonActionPerformed(evt);
            }
        });
        jPanel2.add(generatePayslipButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, 120, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtID11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID11ActionPerformed

    private void txtID10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID10ActionPerformed

    private void backToPESelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToPESelectionActionPerformed
        this.setVisible(false);
        PayrollEmployeeSelection back = new PayrollEmployeeSelection();
        back.setVisible(true);
    }//GEN-LAST:event_backToPESelectionActionPerformed

    private void txtID7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID7ActionPerformed

    private void txtID6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID6ActionPerformed

    private void txtID5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID5ActionPerformed

    private void txtID4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID4ActionPerformed

    private void txtID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID1ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void BacktoDB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacktoDB1ActionPerformed
        this.setVisible(false);
        AdminDashboard back = new AdminDashboard();
        back.setVisible(true);
    }//GEN-LAST:event_BacktoDB1ActionPerformed

    private void generatePayslipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePayslipButtonActionPerformed
        GeneratePayslip GeneratePayslip = new GeneratePayslip();
        GeneratePayslip.setVisible(true);
        SecondPayrollPanel.this.setVisible(false);
    }//GEN-LAST:event_generatePayslipButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondPayrollPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondPayrollPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondPayrollPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondPayrollPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondPayrollPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BacktoDB1;
    private javax.swing.JToggleButton backToPESelection;
    private javax.swing.JToggleButton generatePayslipButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtID10;
    private javax.swing.JTextField txtID11;
    private javax.swing.JTextField txtID4;
    private javax.swing.JTextField txtID5;
    private javax.swing.JTextField txtID6;
    private javax.swing.JTextField txtID7;
    private javax.swing.JLabel txtSelectemployee;
    private javax.swing.JLabel txtSelectemployee1;
    private javax.swing.JLabel txtSelectemployee2;
    private javax.swing.JLabel txtSelectemployee3;
    private javax.swing.JLabel txtSelectemployee4;
    private javax.swing.JLabel txtSelectemployee7;
    private javax.swing.JLabel txtSelectemployee8;
    // End of variables declaration//GEN-END:variables
}
